version: "3.8"

services:
  postgres:
    container_name: shipping-challenge-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: shipping
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  redis:
    container_name: shipping-challenge-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
